// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm5JyRO2uE6_6VtVeDvBgmVHxWDb_EAFU',
    appId: '1:333278686171:web:008a5d118027648c4ed5fe',
    messagingSenderId: '333278686171',
    projectId: 'fit-eats-ba40a',
    authDomain: 'fit-eats-ba40a.firebaseapp.com',
    storageBucket: 'fit-eats-ba40a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfdxvvIPvaMF9-GiNk4FD-ZOTLqKSZQQU',
    appId: '1:333278686171:android:fa0a8ad91121e03a4ed5fe',
    messagingSenderId: '333278686171',
    projectId: 'fit-eats-ba40a',
    storageBucket: 'fit-eats-ba40a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm5JyRO2uE6_6VtVeDvBgmVHxWDb_EAFU',
    appId: '1:333278686171:web:8bd395a657943fd94ed5fe',
    messagingSenderId: '333278686171',
    projectId: 'fit-eats-ba40a',
    authDomain: 'fit-eats-ba40a.firebaseapp.com',
    storageBucket: 'fit-eats-ba40a.firebasestorage.app',
  );
}
